services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nustmarkaz_backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 10080
    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app
    networks:
      - nustmarkaz_network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nustmarkaz_frontend
    environment:
      VITE_BASE_URL: http://localhost:8000
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - nustmarkaz_network
    restart: unless-stopped



networks:
  nustmarkaz_network:
    driver: bridge
